# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modifiablebasemodel',
            name='basemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='removablebasemodel',
            name='modifiablebasemodel_ptr',
        ),
        migrations.RemoveField(
            model_name='simplebasemodel',
            name='basemodel_ptr',
        ),
        migrations.DeleteModel(
            name='ModifiableBaseModel',
        ),
        migrations.DeleteModel(
            name='RemovableBaseModel',
        ),
        migrations.DeleteModel(
            name='SimpleBaseModel',
        ),
    ]
